safe:      true
permalink: pretty
exclude:   [ README.md, Gemfile, vendor, .*, bower.json ]

# Setup
title: "Teisei"
tagline: ""
description: |
    Hi! I'm <a href="http://www.twitter.com/couac">Teisei</a>.
    <br>
    <br>
    Postgraduate student.
    loving sports, photography, geek stuff, also cooking.
    <br>
    <br>
    <small>
    <a href="mailto:teisei.din@gmail.com">teisei.din@gmail.com</a> | <a href="http://pgp.mit.edu/pks/lookup?op=get&search=0xa509bcf1c1274f3b">0xa509bcf1c1274f3b</a>
    </small>

# Used in Atom feeds
url: "http://teisei.github.io"

# About/contact
author:
  name: Teisei
  email: teisei.din@gmail.com


my_linkedin: http://www.linkedin.com/in/cheng-ding-1b38356b
my_github:   http://www.github.com/Teisei
my_twitter:  http://www.twitter.com/teiseiBusy
