safe:      true
permalink: pretty
exclude:   [ README.md, Gemfile, vendor, .*, bower.json ]

# Setup
title: "Cheng Ding"
tagline: ""
description: |
    Hi! I'm <a href="http://www.twitter.com/couac">Will</a>.
    <br>
    <br>
    27 years old. Lifelong learner. Open Source evangelist. Traveler. Triathlete.
    <br>
    <br>
    <small>
    <a href="mailto:will@drnd.me">will@drnd.me</a> | <a href="http://pgp.mit.edu/pks/lookup?op=get&search=0xa509bcf1c1274f3b">0xa509bcf1c1274f3b</a>
    </small>

# Used in Atom feeds
url: "http://williamdurand.fr"

# About/contact
author:
  name: Cheng Ding
  email: teisei.din@gmail.com


my_linkedin: http://www.linkedin.com/in/cheng-ding-1b38356b
my_github:   http://www.github.com/Teisei
my_twitter:  http://www.twitter.com/teiseiBusy
